// src/adapters/catalog-table.ts — GENERATED table (W150): one row per genuine
// LiteLLM chat provider, derived at build time (2026-10-01) from the pinned
// LiteLLM 1.103.0 MIT registries: the LlmProviders enum
// (types/utils.py:4023), the llms/<provider>/chat transformation dirs, and
// llms/openai_like/providers.json. Excluded: vector stores, speech, image/
// video/OCR, observability/gateways, frameworks/agent protocols, meta
// routes, and same-provider route twins (text-completion twins, *_chat,
// *_beta, ollama_chat, hosted_vllm, sagemaker_chat/_nova, qwencloud/
// qwen_ai_platform, text-completion-inception, watsonx_text — collapsed
// into their canonical row). MIT attribution: NOTICE.md. flashx is
// structurally absent — never a row.
import type { AdapterFamily } from "./types.ts";

export type CatalogAuth =
	| "bearer"
	| "api-key-header"
	| "signed"
	| "token-exchange"
	| "none";

export interface CatalogRow {
	name: string;
	family: AdapterFamily;
	tier: 1 | 2 | 3;
	auth: CatalogAuth;
	/** default env var NAME per LiteLLM docs — never a value */
	env?: string;
	/** docs slug under docs.my-website/docs/<slug> */
	docs: string;
}

export const CATALOG_TABLE: readonly CatalogRow[] = [
	{
		name: "openai",
		family: "openai-compat",
		tier: 1,
		auth: "bearer",
		env: "OPENAI_API_KEY",
		docs: "providers/openai",
	},
	{
		name: "anthropic",
		family: "anthropic",
		tier: 1,
		auth: "bearer",
		env: "ANTHROPIC_API_KEY",
		docs: "providers/anthropic",
	},
	{
		name: "azure",
		family: "azure-openai",
		tier: 2,
		auth: "api-key-header",
		env: "AZURE_API_KEY",
		docs: "providers/azure",
	},
	{
		name: "azure_ai",
		family: "azure-openai",
		tier: 2,
		auth: "api-key-header",
		env: "AZURE_AI_API_KEY",
		docs: "providers/azure_ai",
	},
	{
		name: "bedrock",
		family: "bedrock",
		tier: 2,
		auth: "signed",
		env: "AWS_ACCESS_KEY_ID",
		docs: "providers/bedrock",
	},
	{
		name: "sagemaker",
		family: "bedrock",
		tier: 2,
		auth: "signed",
		env: "AWS_ACCESS_KEY_ID",
		docs: "providers/sagemaker",
	},
	{
		name: "amazon_nova",
		family: "bedrock",
		tier: 2,
		auth: "signed",
		env: "AWS_ACCESS_KEY_ID",
		docs: "providers/amazon_nova",
	},
	{
		name: "bedrock_mantle",
		family: "bedrock",
		tier: 2,
		auth: "bearer",
		env: "BEDROCK_API_KEY",
		docs: "providers/bedrock_mantle",
	},
	{
		name: "vertex_ai",
		family: "vertex",
		tier: 2,
		auth: "token-exchange",
		env: "GOOGLE_APPLICATION_CREDENTIALS",
		docs: "providers/vertex",
	},
	{
		name: "gemini",
		family: "vertex",
		tier: 2,
		auth: "api-key-header",
		env: "GEMINI_API_KEY",
		docs: "providers/gemini",
	},
	{
		name: "chatgpt",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "OPENAI_API_KEY",
		docs: "providers/chatgpt",
	},
	{
		name: "xai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "XAI_API_KEY",
		docs: "providers/xai",
	},
	{
		name: "zai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "ZAI_API_KEY",
		docs: "providers/zai",
	},
	{
		name: "cohere",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "COHERE_API_KEY",
		docs: "providers/cohere",
	},
	{
		name: "clarifai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CLARIFAI_API_KEY",
		docs: "providers/clarifai",
	},
	{
		name: "bytez",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "BYTEZ_API_KEY",
		docs: "providers/bytez",
	},
	{
		name: "replicate",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "REPLICATE_API_KEY",
		docs: "providers/replicate",
	},
	{
		name: "huggingface",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "HUGGINGFACE_API_KEY",
		docs: "providers/huggingface",
	},
	{
		name: "together_ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "TOGETHERAI_API_KEY",
		docs: "providers/together_ai",
	},
	{
		name: "openrouter",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "OPENROUTER_API_KEY",
		docs: "providers/openrouter",
	},
	{
		name: "datarobot",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DATAROBOT_API_KEY",
		docs: "providers/datarobot",
	},
	{
		name: "ai21",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "AI21_API_KEY",
		docs: "providers/ai21",
	},
	{
		name: "baseten",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "BASETEN_API_KEY",
		docs: "providers/baseten",
	},
	{
		name: "vllm",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/vllm",
	},
	{
		name: "nlp_cloud",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NLP_CLOUD_API_KEY",
		docs: "providers/nlp_cloud",
	},
	{
		name: "petals",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/petals",
	},
	{
		name: "oobabooga",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/oobabooga",
	},
	{
		name: "ollama",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/ollama",
	},
	{
		name: "deepinfra",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DEEPINFRA_API_KEY",
		docs: "providers/deepinfra",
	},
	{
		name: "perplexity",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "PERPLEXITYAI_API_KEY",
		docs: "providers/perplexity",
	},
	{
		name: "mistral",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MISTRAL_API_KEY",
		docs: "providers/mistral",
	},
	{
		name: "groq",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GROQ_API_KEY",
		docs: "providers/groq",
	},
	{
		name: "gigachat",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GIGACHAT_CREDENTIALS",
		docs: "providers/gigachat",
	},
	{
		name: "nvidia_nim",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NVIDIA_NIM_API_KEY",
		docs: "providers/nvidia_nim",
	},
	{
		name: "cerebras",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CEREBRAS_API_KEY",
		docs: "providers/cerebras",
	},
	{
		name: "volcengine",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "VOLCENGINE_API_KEY",
		docs: "providers/volcengine",
	},
	{
		name: "codestral",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CODESTRAL_API_KEY",
		docs: "providers/codestral",
	},
	{
		name: "dashscope",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DASHSCOPE_API_KEY",
		docs: "providers/dashscope",
	},
	{
		name: "modelscope",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MODELSCOPE_API_KEY",
		docs: "providers/modelscope",
	},
	{
		name: "moonshot",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MOONSHOT_API_KEY",
		docs: "providers/moonshot",
	},
	{
		name: "publicai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "PUBLICAI_API_KEY",
		docs: "providers/publicai",
	},
	{
		name: "v0",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "V0_API_KEY",
		docs: "providers/v0",
	},
	{
		name: "morph",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MORPH_API_KEY",
		docs: "providers/morph",
	},
	{
		name: "lambda_ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "LAMBDA_API_KEY",
		docs: "providers/lambda_ai",
	},
	{
		name: "inception",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "INCEPTION_API_KEY",
		docs: "providers/inception",
	},
	{
		name: "deepseek",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DEEPSEEK_API_KEY",
		docs: "providers/deepseek",
	},
	{
		name: "sambanova",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SAMBANOVA_API_KEY",
		docs: "providers/sambanova",
	},
	{
		name: "maritalk",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MARITALK_API_KEY",
		docs: "providers/maritalk",
	},
	{
		name: "cloudflare",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CLOUDFLARE_API_KEY",
		docs: "providers/cloudflare",
	},
	{
		name: "xinference",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/xinference",
	},
	{
		name: "fireworks_ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "FIREWORKS_AI_API_KEY",
		docs: "providers/fireworks_ai",
	},
	{
		name: "friendliai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "FRIENDLIAI_API_KEY",
		docs: "providers/friendliai",
	},
	{
		name: "featherless_ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "FEATHERLESS_AI_API_KEY",
		docs: "providers/featherless_ai",
	},
	{
		name: "watsonx",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "WATSONX_API_KEY",
		docs: "providers/watsonx",
	},
	{
		name: "triton",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/triton",
	},
	{
		name: "predibase",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "PREDIBASE_TOKEN",
		docs: "providers/predibase",
	},
	{
		name: "databricks",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DATABRICKS_API_KEY",
		docs: "providers/databricks",
	},
	{
		name: "empower",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "EMPOWER_API_KEY",
		docs: "providers/empower",
	},
	{
		name: "github",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GITHUB_TOKEN",
		docs: "providers/github",
	},
	{
		name: "docker_model_runner",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/docker_model_runner",
	},
	{
		name: "tencent",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "TENCENT_API_KEY",
		docs: "providers/tencent",
	},
	{
		name: "llamafile",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/llamafile",
	},
	{
		name: "lm_studio",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/lm_studio",
	},
	{
		name: "galadriel",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GALADRIEL_API_KEY",
		docs: "providers/galadriel",
	},
	{
		name: "nebius",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NEBIUS_API_KEY",
		docs: "providers/nebius",
	},
	{
		name: "novita",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NOVITA_API_KEY",
		docs: "providers/novita",
	},
	{
		name: "sap",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SAP_API_KEY",
		docs: "providers/sap",
	},
	{
		name: "charity_engine",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/charity_engine",
	},
	{
		name: "github_copilot",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GITHUB_COPILOT_PAT",
		docs: "providers/github_copilot",
	},
	{
		name: "snowflake",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SNOWFLAKE_TOKEN",
		docs: "providers/snowflake",
	},
	{
		name: "gradient_ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GRADIENT_AI_API_KEY",
		docs: "providers/gradient_ai",
	},
	{
		name: "meta_llama",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "LLAMA_API_KEY",
		docs: "providers/meta_llama",
	},
	{
		name: "nscale",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NSCALE_API_KEY",
		docs: "providers/nscale",
	},
	{
		name: "hyperbolic",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "HYPERBOLIC_API_KEY",
		docs: "providers/hyperbolic",
	},
	{
		name: "heroku",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "HEROKU_API_KEY",
		docs: "providers/heroku",
	},
	{
		name: "aiml",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "AIML_API_KEY",
		docs: "providers/aiml",
	},
	{
		name: "cometapi",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "COMETAPI_API_KEY",
		docs: "providers/cometapi",
	},
	{
		name: "oci",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "OCI_TOKEN",
		docs: "providers/oci",
	},
	{
		name: "manus",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MANUS_API_KEY",
		docs: "providers/manus",
	},
	{
		name: "ovhcloud",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "OVHCLOUD_API_KEY",
		docs: "providers/ovhcloud",
	},
	{
		name: "scaleway",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SCALEWAY_API_KEY",
		docs: "providers/scaleway",
	},
	{
		name: "lemonade",
		family: "openai-compat",
		tier: 3,
		auth: "none",
		docs: "providers/lemonade",
	},
	{
		name: "minimax",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "MINIMAX_API_KEY",
		docs: "providers/minimax",
	},
	{
		name: "synthetic",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SYNTHETIC_API_KEY",
		docs: "providers/synthetic",
	},
	{
		name: "apertis",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "APERTIS_API_KEY",
		docs: "providers/apertis",
	},
	{
		name: "nano-gpt",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NANO_GPT_API_KEY",
		docs: "providers/nano-gpt",
	},
	{
		name: "poe",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "POE_API_KEY",
		docs: "providers/poe",
	},
	{
		name: "chutes",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CHUTES_API_KEY",
		docs: "providers/chutes",
	},
	{
		name: "neosantara",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "NEOSANTARA_API_KEY",
		docs: "providers/neosantara",
	},
	{
		name: "parasail",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "PARASAIL_API_KEY",
		docs: "providers/parasail",
	},
	{
		name: "xiaomi_mimo",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "XIAOMI_MIMO_API_KEY",
		docs: "providers/xiaomi_mimo",
	},
	{
		name: "tensormesh",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "TENSORMESH_API_KEY",
		docs: "providers/tensormesh",
	},
	{
		name: "libertai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "LIBERTAI_API_KEY",
		docs: "providers/libertai",
	},
	{
		name: "pinstripes",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "PINSTRIPES_API_KEY",
		docs: "providers/pinstripes",
	},
	{
		name: "cognition",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "COGNITION_API_KEY",
		docs: "providers/cognition",
	},
	{
		name: "scx-ai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SCX_AI_API_KEY",
		docs: "providers/scx-ai",
	},
	{
		name: "darkbloom",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "DARKBLOOM_API_KEY",
		docs: "providers/darkbloom",
	},
	{
		name: "meta",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "META_API_KEY",
		docs: "providers/meta",
	},
	{
		name: "cursor",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CURSOR_API_KEY",
		docs: "providers/cursor",
	},
	{
		name: "gdc",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GDC_API_TOKEN",
		docs: "providers/gdc",
	},
	{
		name: "veniceai",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "VENICE_API_KEY",
		docs: "providers/venice",
	},
	{
		name: "abliteration",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "ABLITERATION_API_KEY",
		docs: "providers/abliteration",
	},
	{
		name: "llamagate",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "LLAMAGATE_API_KEY",
		docs: "providers/llamagate",
	},
	{
		name: "gmi",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "GMI_API_KEY",
		docs: "providers/gmi",
	},
	{
		name: "sarvam",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "SARVAM_API_KEY",
		docs: "providers/sarvam",
	},
	{
		name: "aihubmix",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "AIHUBMIX_API_KEY",
		docs: "providers/aihubmix",
	},
	{
		name: "crusoe",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "CRUSOE_API_KEY",
		docs: "providers/crusoe",
	},
	{
		name: "empiriolabs",
		family: "openai-compat",
		tier: 3,
		auth: "bearer",
		env: "EMPIRIOLABS_API_KEY",
		docs: "providers/empiriolabs",
	},
];
